on: 
  push:
    branches: 
      - main
    
jobs:
  job1:
    runs-on: [self-hosted, linux, X64, research]

    steps:  
      - name: configure github repo
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/ORG/repos \
            -d '{"name":"Hello-World","description":"This is your first repository","homepage":"https://github.com","private":false,"has_issues":true,"has_projects":true,"has_wiki":true}'
